# Generated by Django 5.1.6 on 2025-02-19 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Votos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_votadas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eLOGiar.categoria')),
                ('pessoa_votadas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_recebidos', to='eLOGiar.usuarios')),
                ('pessoa_votando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_feitos', to='eLOGiar.usuarios')),
            ],
            options={
                'unique_together': {('pessoa_votando', 'pessoa_votadas', 'categoria_votadas')},
            },
        ),
    ]
