# Generated by Django 5.1.6 on 2025-02-20 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLOGiar', '0002_votos_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votos',
            name='mensagem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='votos',
            name='pessoa_votando',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eLOGiar.usuarios'),
        ),
    ]
