# Generated by Django 5.1.6 on 2025-04-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLOGiar', '0003_alter_votos_mensagem_alter_votos_pessoa_votando'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='cargo',
            field=models.CharField(choices=[('Gestão', 'Gestão'), ('Colaborador', 'Colaborador')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='setor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
